include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true 
    use_super_parameters: true
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true

analyzer: 
  exclude: ["**.freezed.dart", "**.g.dart"]

  errors: 
    invalid_annotation_target: ignore